feat: Implement Canvas Drawing Event (Pen Mode)
boostcampwm-2024/web30-stop-troublepainter pull request #33
Opened 2024-11-10 10:19 UTC by AeuJoung

---
name: Pull Request Template
about: Review of Issue Results
title: '${작업 키워드}: '
labels: ''
assignees: ''
---

## 📂 작업 내용

closes #16 

- [x] 클릭 시 그리기 기능 추가 (PC)
- [x] 터치 시 그리기 기능 추가 (Mobile)

## 💡 자세한 설명

- 클릭(pc) 및 터치(mobile) 시 캔버스에 선을 그릴 수 있습니다.

## 📗 참고 자료 & 구현 결과 (선택)

## 📢 리뷰 요구 사항 (선택)

- 첫 pr이라서, 형식 맞는지 확인 부탁드립니다.

## 🚩 후속 작업 (선택)
- [ ] 클릭한 상태에서 캔버스 밖으로 나갔다가 다시 들어왔을 때 그려진다.  
- [ ] 클릭하여 빠르게 그렸을 때 모서리까지 제대로 그려진다.

## ✅ 셀프 체크리스트

- [x] PR 제목을 형식에 맞게 작성했나요?
- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있나요? (`main`이 아닙니다.)
- [x] 이슈는 close 했나요?
- [x] Reviewers, Labels를 등록했나요?
- [x] 작업 도중 문서 수정이 필요한 경우 잘 수정했나요?
- [ ] 테스트는 잘 통과했나요?
- [x] 불필요한 코드는 제거했나요?

2024-11-10 11:19 UTC, rhino-ty reviewed
`CANVAS_SIZE_WIDTH` 같은 걸 보니 아직 반응형은 구현 안된거죠?

4:3으로 반응형 구현 및 작은 화면에서도 그대로 그릴 수 있게 해줘야하는 기능이라 중요하다고 생각해서요! 
저의 UI와 합쳐서 추후에 구현해도 됩니다!

2024-11-10 11:35 UTC, AeuJoung commented
> `CANVAS_SIZE_WIDTH` 같은 걸 보니 아직 반응형은 구현 안된거죠?
> 
> 4:3으로 반응형 구현 및 작은 화면에서도 그대로 그릴 수 있게 해줘야하는 기능이라 중요하다고 생각해서요! 저의 UI와 합쳐서 추후에 구현해도 됩니다!

넵 일단 이슈 나눠놓은거 맞춰서 로컬에서 작업한 페인트 툴 까지 옮겨놓는 중입니다. 다 옮긴 후 반응형부터 작업해보겠습니다. : )

2024-11-10 13:47 UTC, choiseona reviewed
고생하셨습니다!!

2024-11-10 13:47 UTC, choiseona commented on client/src/components/canvas/MainCanvas.tsx
> +  const { top, left } = canvas.getBoundingClientRect(); // 캔버스의 뷰포트 기준 위치
오 nativeEvent라는게 있군요 처음 봅니다! 그냥 event랑은 뭐가 다른지 찾아봐야겠네용

2024-11-10 13:47 UTC, choiseona commented on client/src/components/canvas/MainCanvas.tsx
> +    if (!canvas) return;
중복되는 로직인 것 같습니다!

2024-11-10 14:04 UTC, AeuJoung commented on client/src/components/canvas/MainCanvas.tsx
> +    if (!canvas) return;
오 넘 감사합니다 :D

2024-11-11 07:09 UTC, kwaksj329 requested changes
고생하셨습니다! 코멘트만 한번 검토해주세요~!

2024-11-11 07:09 UTC, kwaksj329 commented on client/src/components/canvas/MainCanvas.tsx
> +    }
`getDrawPoint` 함수에서는 throw Error로 로 에러를 발생시키는 반면 이 try-catch 문에서는 `console.error`로 에러 로깅만 하고 있습니다.
일관성을 위해 모든 에러 발생 가능 지점에서는 `throw Error`를 사용하고 차후에 최상위 컴포넌트에서 일괄적으로 처리하는 것이 더 좋은 방식일 것 같습니다.

2024-11-11 07:09 UTC, kwaksj329 commented on client/src/components/canvas/MainCanvas.tsx
> +    return [event.nativeEvent.offsetX, event.nativeEvent.offsetY];
```suggestion
  if (e.nativeEvent instanceof MouseEvent) {
    return [e.nativeEvent.offsetX, e.nativeEvent.offsetY];
  }
```

2024-11-11 08:24 UTC, kwaksj329 approved these changes

2024-11-11 08:25 UTC, choiseona approved these changes

2024-11-11 08:39 UTC, merged